[template] change the Date scalar to AWSDate and add some logic to merge and update graphql schemas

diff --git a/templatespec.yaml b/templatespec.yaml
--- a/templatespec.yaml
+++ b/templatespec.yaml
@@ -22,13 +22,22 @@ phases:
       - |
         graphql-schema-utilities \
         -s "./${GRAPHQL_FOLDER_PATH}/schema-definition/**/*.graphql" \
-        -o "./${GRAPHQL_FOLDER_PATH}/schema.graphql-${CODEBUILD_BUILD_NUMBER}"
+        -o "./${GRAPHQL_FOLDER_PATH}/schema-${CODEBUILD_BUILD_NUMBER}.graphql"
       - rm ./${GRAPHQL_FOLDER_PATH}/schema-definition -r
       - echo "changing parameter GraphQLSchemaFileName"
+      - diff schema-*.graphql
+      # "$?" variable that store the exit code of the last command
       - |
-        cat cfn-templates/parameters.json | \
-        fx ".map($(cat cfn-templates/mapParams.js))" \
-        > cfn-templates/parameters.json
+        [ $? -qt 0 ] && { \
+          echo "need to update" \
+          diff schema-*.graphql \
+          cat cfn-templates/parameters.json | \
+          fx ".map($(cat cfn-templates/mapParams.js))" \
+          > cfn-templates/parameters.json \
+        } || { \
+          echo "GraphQL schemas are equals, there is no need to update" \
+          rm ./${GRAPHQL_FOLDER_PATH}/schema-definition \
+        }
 
   build:
     commands:
